experiment_name : 'hazelnut'
dataroot :        "./Datasets/mvtec/carpet"
experiment_path : './Experiments/GANomaly/mvtec/carpet'
checkpoint_save : "./Experiments/GANomaly/mvtec/carpet/checkpoint"
checkpoint_load : "./Experiments/GANomaly/mvtec/carpet/checkpoint/checkpoint_best.pt"
log_path :        "./Experiments/GANomaly/mvtec/carpet/carpet.log"
start_epoch : 1
finish_epoch : 200
manualseed : 42

batchSize : 64
imageSize_h : 64
imageSize_w : 64
nc : 3
nz : 80
ngf : 64
n_extra_layers : 0

device : 'gpu'
gpu_ids : 0
ngpu : 1

lr : 0.0002
b1 : 0.5
b2 : 0.999
w_adv : 1
w_con : 40
w_lat : 1
reset_disc_value : 1e-5
sample_interval : 50