experiment_name : 'station'
dataroot :        "../Datasets/station"
experiment_path : "./Experiments/STFPM/station"
weight_path :     "./Experiments/STFPM/best.pth.tar"
checkpoint_save : "./Experiments/STFPM/station/checkpoint"
checkpoint_load : "../checkpoint/STFPM/Station/checkpoint/checkpoint_best.pt"
log_path :        "./Experiments/STFPM/station/station.log"

start_epoch : 1
finish_epoch : 200
manualseed : 42

batchSize : 64
imageSize_h : 172
imageSize_w : 128
lossSize_h : 86
lossSize_w : 64

device : 'gpu'
gpu_ids : 0
ngpu : 1

lr : 0.4
momentum : 0.9
weight_decay : 1e-4




sample_interval : 20